# Basic Site Settings
#------------------------------------------------
title: Darin Hawley
description: I like taking photos.
show_downloads: false

# Theme
#------------------------------------------------
theme: jekyll-theme-cayman

# Build Settings
#------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
